language: 'python'
sudo: false
python:
  - "2.7.11"

env:
  global:
    - 'AWS_DEFAULT_REGION=us-east-1'
    - 'AWS_ACCESS_KEY_ID=AKIAJGARB35NA2OFFNYQ'
    - secure: "n91X5ZkK8ETXp33zLFF4v9jNubhZvfdZB1sd7/ZUt1sqR6K3rPThp7/xG6JFS4zAOIK+mv0lBgViIK0bQWTLg/Sb7t9ZVfkP21/MWDvMZUYpPUZ63AbdRS+nHrfgOkG5O8HxoitArw6e3Vu2s+UStHMoptWCfUt4TqEr+6BX3/oZuDpsm8ZnQr7zsWq+oDfRKbqwZgpd+0G9BQmuuAC7Wcamx4ZDo+acA286dYiA19CPdMRDVCZTFoLODxnPPGtjg11rBCn2bvBCynAsawPdq506hfkLSDasrOno2UH9DqRuTdghaUGlRk/B63HiRzEDazvov7QlsWcB5pX6b2GlmpH3dd0TWaFxZEf0wQFVhfW+BSFz1Nhxx40pwDLAudWDrK39tF/h16QQ/FF629zAkYZKimjo3RpgkzLstsGsXBH26x+lruKNprv+4zF+UIOEsv4AUNrb+iAbLC4eF5aMYHeIeubV6qbj5Fg9fwPJYIrYkIUH6C3YF3pnqtmtc3acxVm+R/cZt+ksI/kXnPhhYoN11IClqTyJTdnjqxrEwjvVrktAKCkloKr1Rzq/iDuYa5mnikSZ4aZkKHFCANZVWQZZOiDSCySyc1UTsJSEWjNzf52BjPcGqqSEr1zP37bbPBXKosWibBMXMBEM7T/hM+zMyqOdj8kQnGoLGxZXq8E="

before_install:
  - 'pip install awscli'

install:
  - 'make install'

script:
  - 'make test'

after_success:
  - './env/bin/coveralls'

before_deploy:
  - 'make lambda'

deploy:
  - provider: 'script'
    script: '
      aws lambda
        update-function-code
        --function-name "tidycat-environment-backend-staging"
        --zip-file fileb://lambda.zip
        --publish'
    skip_cleanup: true
    on:
      repo: 'tidycat/environment-backend'
      branch: 'master'
  - provider: 'script'
    script: '
      aws lambda
        update-function-code
        --function-name "tidycat-environment-backend"
        --zip-file fileb://lambda.zip
        --publish'
    skip_cleanup: true
    on:
      repo: 'tidycat/environment-backend'
      tags: true
  - provider: 'releases'
    api_key:
      secure: "nCxp2Mhe2W0IQ+LGhfe+xTtcCoGDIxZSI6WZVmtz/4VriRdNQJnIf3GUSJ6fbmW3OfuGTClPx+9BrCIWej1GWotJlFuqfPT6M3xIlhy7LuHWNQEcVPhnAFkdx5ex4tqNEjYz5+viv5oaZDs9pJ0SVoMh4DffSu2l/yZyZzvISd/wdki5Ldbt/bK4eUKbWnO6/tAMhJzP1mibVxCb65QDF44JuNRnLi1BsopExTUgB/Mox+BNJFw/GXMO60gy/5MDLRDdpqAiP1P5Z7kwD1xtOUBJHB9QSuyWukNnusDvA6zmOcIHoHuzqFOs1MvcTjoSZkzBfMZCM2ZE0J/GERL1kj0jN/ZFCkxyjMX2lNyaQWapg4ummKr7sUeXX5yx/uXrzAwbAsJ/o/xNQ0hPkaBKZoTUr5xhIL1MfPLSp2hRorFcDyMI5mOdyR8+V2d2pFtg9xyjLaiuMvZVgHgRKUtiIeGK8sIqZYNER8U8r9bmvRb/uqj1Z+yT7++H3sw+2FXmEv8/mtFUhzgFyubCakQwAiFS5Y/yMQxHDRNDVBRg4sXIjx41OCUEt9IfS0ZXQzAzl99RwHlWHPPGOtymV/Ajz80gjakIq7bp4zWueD15xs3Sc6BpY/WlVVEY1gvI+1I7hLSJrjtjX3BtwZbJr4Xe9HeeqTULSgouL7RjBjFYD/o="
    file: 'lambda.zip'
    skip_cleanup: true
    on:
      repo: 'tidycat/environment-backend'
      tags: true

notifications:
  email: false
  irc:
    channels:
      - secure: "G3BrC23/3o5UNmDWAOYOEe/XR6U4+UE3hpAOM7SQXj5m5M1ovCh0jJ4aVkc1J36EznoStMY2DQt9oTWRrGUW9UZTtYeyD95BU0qsI0+p0Etwdt1KbLrFbcRL45FMonXSgwCJOsS+Kr5P0SJALfWkoN1o6Rh7feYO8N9hLLFNKJteecx2Rufuo14IF2OrFXS+kNZhPxIInljVmynuBugL0IDCCwsQeRWOxoqOOQk6C3q7hJpjl2v5oiJXesY2ulp5gQMGwjV91qk3o3h33IRMqSxWGQ82CtfhPzfrX7ibhxlZVZFMjrQ4CTDoQLpBA3f3jPA3dgMQJ0mcpFdqCFOKufHwpCY8/BPKNWvBLABt60VTwKW9CSFhadi8u7lJ2wxUyBhzH3SQZAF04sDOZN/Eh3XNxYRS2loREn+bbcUp6erSJEcz85cA33sz/niSDkGde1IKOqlV7xdlOo9TmbAyqdW9taPkSeaT85VB1HKcjtndaRi73qaYQczFj1iseDej40c4iG+SkBqsaDr4DUIg7pCSdniIfxtCKLgjIgHqjDrFXgEucbkEMgqoyw/D0ykoOg6V9rgwGa1Di6XW+jap+qGfqETyVc77/nr/Lh2YMGB+to+lA2l/SPZHBpnVSL9yokvc+b85GX6+C21QCTRicgp14T4mJYB8cq8PtJCY5HY="
    on_success: "change"
    on_failure: "change"
